spring:
  application:
    name: multimoduletest
  datasource:
    url: jdbc:postgresql://localhost:5432/multimoduletest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
